# based on shawn1m/overture (MIT LICENSE)
# The MIT License (MIT)
# Copyright (c) 2019 import-yuefeng
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

language: go
go:
- 1.12.x
addons:
  apt:
    packages:
    - python3
script:
- python3 ./build.py -create-sample
before_deploy:
- go version
- ls -al
- python3 ./build.py -build
deploy:
  provider: releases
  api_key:
    secure: LMhCmYeVCCHH0OfApJslNSrNSmolmRuWqhT/1QsBTt7q1yeDy4pW8b4tKhn6PxnXWboidV70Wn0kPpc5DOBAnFd4dzrbyHd4CVfubo/Xw/D9EZ9FMWXqYZDYIIGC+TJMNuDl1M4ZL/JwY+95yVYrwUbbbHq2Q+y+NOI5z5T7FCcuecEBRpX7sg5warSqLPbkkKi7lqThwaxuOou7ylNuTopaLczOfzw0Twv55TscnLrZgPIv6FlKRbyrZDJwEIuFMBhyw2M2n6HEr52GMjsesCmeBbUUq5cqHb4aFBzeDM7lDYT2RAz8vXpiMZYwAvtsy76Vp4mp4N7wFOPYstoi26JUALBDA3VoQvAC7FTQlY93eMwlD7HavqPo4xvXN46Pyq7oika6n/FFHc+jzDSXl1Sfupi9v7KYW8nvFqxSkLva+GrIr9Vm6AeIzOFu1FfuiuRY0nwpbKTkGFs9a0geqLGGvYbhoioMU6S0itaLoQpeCfcF+CgRCDYXj3Jk752lSZFpRfI+l7LCed5QBr4jKjE6IMuIIUVLM1j/nyzBUOFWUyNugJGFnDJtjtimZuzcHrmHoSFzrBx4mTwltBdpSRh2DftT4VXhst78qg4gO/dOWkut255oiF/s0mTd0oA4doESuvc/FiDXiaB+BqI5A3UfdWv+LBbBGydN9QmInJs=
  file:
    - smartDNS-darwin-amd64.zip
    - smartDNS-linux-386.zip
    - smartDNS-linux-amd64.zip
    - smartDNS-linux-arm.zip
    - smartDNS-linux-arm64.zip
    - smartDNS-linux-mips-softfloat.zip
    - smartDNS-linux-mips-hardfloat.zip
    - smartDNS-linux-mipsle-softfloat.zip
    - smartDNS-linux-mipsle-hardfloat.zip
    - smartDNS-linux-mips64.zip
    - smartDNS-linux-mips64le.zip
    - smartDNS-freebsd-386.zip
    - smartDNS-freebsd-amd64.zip
    - smartDNS-windows-386.zip
    - smartDNS-windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true

